# Generated by Django 4.2.5 on 2023-09-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApi', '0002_alter_employee_emp_code_alter_employee_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(max_length=13),
        ),
    ]
